### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by girikuncoro** [kata-ai/kata-cli#12]
Make `CONTRIBUTING.md` that explains how to start contributing to this repo, this is important for ordinary developers outside kata.ai to start contributing. (i.e. Fork the repo, add test, etc.) Example from `kubectl` CLI sig group: https://github.com/kubernetes/community/blob/master/sig-cli/CONTRIBUTING.md

though this is too intense, perhaps something much simpler is also acceptable.

**Comment by aliarham11** [comment]
Done in commit f4505a79ddcb0a9c3e13b9e8e78bc393a232c6d3
