### ISSUE TITLE
Kata-cli freezing on login 

### ISSUE THREAD

**Issue by mragit** [kata-ai/kata-cli#134]
Ketika melakukan login lewat kata ai , stuck setelah memasukkan username dan password. 

![](https://i.imgur.com/zyZuOq7.jpg)

Apakah mungkin berkaitan dengan useragent yg di warn oleh npm diatas,

**Comment by Shiyinq** [comment]
@mragit 
Coba di update aja ke versi terbaru.
Sekarang versi paling stabil 2.6.0  `npm i -g kata-cli@2.6.0`

**Comment by dwikresno** [comment]
klo masih belum bisa coba download gitbash
