### ISSUE TITLE
New version information when push patch

### ISSUE THREAD

**Issue by girikuncoro** [kata-ai/kata-cli#14]
Would love to see new version shown as part of CLI result when I patch it:

instead of 
```
$ kata push --rev patch
UPDATED BOT SUCCESSFULLY
```

would like this one better:
```
$ kata push --rev patch
UPDATED BOT SUCCESSFULLY WITH VERSION 0.0.5
```

**Comment by prakashdivyy** [comment]
Thanks @girikuncoro 
I will working on this issue

**Comment by prakashdivyy** [comment]
Waiting for PR #30
