### ISSUE TITLE
Akses parameter

### ISSUE THREAD

**Issue by irpankusuma** [kata-ai/kata-cli#145]
Dear team kata

Tanya dong, klo dlm file bot.yaml section methods
Kan itu akses javascript, klo saya mau akses payload atau data gimana caranya ya dri javascript itu

**Comment by oktavianidewi** [comment]
hai @irpankusuma

untuk mengakses value dari object `message`, `context`, `data`, `options` bisa dengan passing parameter object tersebut ke method function. berikut ini contohnya: 

```
methodvoucher(data,options): "
    let voucher = options.voucher || null;
    data.voucher =  voucher || data.voucher; 
    let resp = '';
    if (voucher == null){
      resp = 'Vouchernya udah kamu redeem lho :) ini kode kamu '+ data.voucher;
    } else {
      resp = 'Ini kode voucher kamu '+ data.voucher;
    }
    return {
      type: 'text',
      content: resp
    }
  " 
```

**Comment by indraaristya** [comment]
> Dear team kata
> 
> Tanya dong, klo dlm file bot.yaml section methods
> Kan itu akses javascript, klo saya mau akses payload atau data gimana caranya ya dri javascript itu

Halo, untuk mengakses data/context/payload lewat method bisa menggunakan contoh berikut.

```
someMethod(ctx):
	const contohData =  ctx.data.someName;
	const contohContext = ctx.context.someName;
```

**Comment by oktavianidewi** [comment]
mas @irpankusuma, bisa di-cek jawaban2 di atas ya. terimakasih.
