### ISSUE TITLE
kata login with wrong password but logged in

### ISSUE THREAD

**Issue by sofianhw** [kata-ai/kata-cli#21]
Dear Kata,

When I try to kata push it say you are not authorize 
and I just realize that I enter wrong password 
but system say "logged in"

![screen shot 2017-11-27 at 14 22 43](https://user-images.githubusercontent.com/1507989/33255181-e7b14a68-d37e-11e7-956d-0b230634f6ad.png)

**Comment by prakashdivyy** [comment]
Thanks @sofianhw I will working on this issue 😄

**Comment by prakashdivyy** [comment]
#22

**Comment by aliarham11** [comment]
[CLOSED with https://github.com/kata-ai/kata-cli/pull/22]
