### ISSUE TITLE
View log messages after deploying bots

### ISSUE THREAD

**Issue by abhishtagatya** [kata-ai/kata-cli#47]
Dear Kata Team,

I'm having problems with my LINE Bot, I tried following your documentation and after I set up the webhooks and verified the URL, the bot wouldn't replied to me at all. I would like to know where I messed up by seeing the logs of my chat bot but kata-cli doesn't seem to have that feature (or atleast I didn't know where to look).

Also the emulator works but when I deployed it to LINE it didn't. Can anyone help me with this?

Thank You in advance :+1:

**Comment by Shiyinq** [comment]
to check error in bot, you can use kata console -> enter -> text("hi") -> enter, you can see the error.
-
or go to https://platform.kata.ai -> find menu error logs, you can see the error.

i hope this can help you :)
