### ISSUE TITLE
Can't deploy with kata-cli

### ISSUE THREAD

**Issue by asamsulfat** [kata-ai/kata-cli#77]
![not found](https://user-images.githubusercontent.com/17421945/49911804-5c41fa00-feba-11e8-8024-1b2cf9507a7f.png)

I'd like to code with my own text editor, so I use kata-cli when deploy the next version.
But today it's not working, it say not found.

**Comment by prakashdivyy** [comment]
Hello

In that time we upgrading our platform to the latest version. Now its working with new features and also you must upgrade kata-cli to the latest version.
