### ISSUE TITLE
Add CLI versioning

### ISSUE THREAD

**Issue by girikuncoro** [kata-ai/kata-cli#8]
In order to maintain features and help end users debugging easily, it would be great to add command to show version of kata-cli. Currently there's one command `kata versions` which list out bot versions, which is IMO missplaced. 

I would expect something like `kata version`, to show current version of my CLI, for example:
```
$ kata version
Kata CLI version 1.0, commit hash XXXX
```
This will help me if I face problem related to CLI, which really happened to one of the users in Japan. Perhaps this new functionality + some docs on changelogs would help a lot.

Inspired by `kubectl` and many more
```
$ kubectl version
$ go version
$ node version
```

**Comment by aliarham11** [comment]
Done in commit f4505a79ddcb0a9c3e13b9e8e78bc393a232c6d3
